/*
 * AntiFriezeAboutBox.java
 */

package com.wms.antifreeze.gui;

import org.jdesktop.application.Action;

public class AF_About extends javax.swing.JDialog {
    private static final long serialVersionUID = -2615761412980073167L;

    public AF_About(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        javax.swing.JLabel versionLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
        javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
        javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        splashImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getResourceMap(AF_About.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setForeground(resourceMap.getColor("jPanel1.foreground")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        jScrollPane1.setFocusable(false);
        jScrollPane1.setFont(resourceMap.getFont("jScrollPane1.font")); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setText(resourceMap.getString("jTextPane1.text")); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        versionLabel.setBackground(resourceMap.getColor("versionLabel.background")); // NOI18N
        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
        versionLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
        versionLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        versionLabel.setName("versionLabel"); // NOI18N
        versionLabel.setOpaque(true);

        appVersionLabel.setBackground(resourceMap.getColor("versionLabel.background")); // NOI18N
        appVersionLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        appVersionLabel.setText(resourceMap.getString("appVersionLabel.text")); // NOI18N
        appVersionLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        appVersionLabel.setName("appVersionLabel"); // NOI18N
        appVersionLabel.setOpaque(true);

        vendorLabel.setBackground(resourceMap.getColor("versionLabel.background")); // NOI18N
        vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
        vendorLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        vendorLabel.setText(resourceMap.getString("vendorLabel.text")); // NOI18N
        vendorLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vendorLabel.setName("vendorLabel"); // NOI18N
        vendorLabel.setOpaque(true);

        appVendorLabel.setBackground(resourceMap.getColor("versionLabel.background")); // NOI18N
        appVendorLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        appVendorLabel.setText(resourceMap.getString("appVendorLabel.text")); // NOI18N
        appVendorLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        appVendorLabel.setName("appVendorLabel"); // NOI18N
        appVendorLabel.setOpaque(true);

        homepageLabel.setBackground(resourceMap.getColor("versionLabel.background")); // NOI18N
        homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
        homepageLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        homepageLabel.setText(resourceMap.getString("homepageLabel.text")); // NOI18N
        homepageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        homepageLabel.setName("homepageLabel"); // NOI18N
        homepageLabel.setOpaque(true);

        appHomepageLabel.setBackground(resourceMap.getColor("versionLabel.background")); // NOI18N
        appHomepageLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        appHomepageLabel.setText(resourceMap.getString("appHomepageLabel.text")); // NOI18N
        appHomepageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        appHomepageLabel.setName("appHomepageLabel"); // NOI18N
        appHomepageLabel.setOpaque(true);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(homepageLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(appHomepageLabel))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(vendorLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(appVendorLabel))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(versionLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(appVersionLabel))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(versionLabel)
                    .add(appVersionLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(vendorLabel)
                    .add(appVendorLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(homepageLabel)
                    .add(appHomepageLabel))
                .add(10, 10, 10))
        );

        jPanel1.setBounds(60, 120, 450, 260);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getActionMap(AF_About.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setIconTextGap(0);
        closeButton.setName("closeButton"); // NOI18N
        closeButton.setOpaque(false);
        closeButton.setBounds(510, 350, -1, -1);
        jLayeredPane1.add(closeButton, javax.swing.JLayeredPane.MODAL_LAYER);

        splashImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        splashImage.setIcon(resourceMap.getIcon("splashImage.icon")); // NOI18N
        splashImage.setText(resourceMap.getString("splashImage.text")); // NOI18N
        splashImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        splashImage.setName("splashImage"); // NOI18N
        splashImage.setBounds(0, 0, 600, 430);
        jLayeredPane1.add(splashImage, javax.swing.JLayeredPane.PALETTE_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel splashImage;
    // End of variables declaration//GEN-END:variables
    
}
