/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AFShopInfo.java
 *
 * Created on Aug 9, 2009, 9:32:15 PM
 */

package com.wms.antifreeze.gui;

import com.wms.antifreeze.AFMgr;
import com.wms.antifreeze.entity.AFShopEntity;
import com.wms.antifreeze.gui.AFViewMgrInterface.AFColor;
import com.wms.util.gui.GUILogInterface;

/**
 *
 * @author Matt
 */
public class AFPreferences extends javax.swing.JDialog {

    /** Creates new form AFShopInfo */
    AFShopEntity afShopInfo = null;
    AFMgr afMgr = null;
    AFViewMgrInterface afViewMgr = null;
    private boolean appStarted = false;

    public AFPreferences(GUILogInterface log, java.awt.Frame parent, AFViewMgrInterface afViewMgr, AFMgr afMgr ) {
        super(parent);
        this.afMgr = afMgr;
        this.afViewMgr = afViewMgr;
        
        initComponents();
        appStarted = true;
        afShopInfo = afMgr.getShopInfo();
        displayShopInfo();

    }



    public void displayShopInfo()
    {
        if( !appStarted )
            return;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        colorsPanel = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        workFlowPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        shopInfoHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getResourceMap(AFPreferences.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(0, 0, 620, 620);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        colorsPanel.setBackground(resourceMap.getColor("colorsPanel.background")); // NOI18N
        colorsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(resourceMap.getColor("colorsPanel.border.highlightColor"), resourceMap.getColor("colorsPanel.border.shadowColor"))); // NOI18N
        colorsPanel.setForeground(afViewMgr.getColorFromAFColor(AFViewMgrInterface.AFColor.InnerPanel));
        colorsPanel.setName("colorsPanel"); // NOI18N

        jColorChooser1.setName("jColorChooser1"); // NOI18N

        javax.swing.GroupLayout colorsPanelLayout = new javax.swing.GroupLayout(colorsPanel);
        colorsPanel.setLayout(colorsPanelLayout);
        colorsPanelLayout.setHorizontalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        colorsPanelLayout.setVerticalGroup(
            colorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorsPanelLayout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("colorsPanel.TabConstraints.tabTitle"), colorsPanel); // NOI18N

        workFlowPanel.setName("workFlowPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Customer Information", "Car Information", "Estimate", "Verify with Customer", "Inventory Parts", "Assign Tech", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout workFlowPanelLayout = new javax.swing.GroupLayout(workFlowPanel);
        workFlowPanel.setLayout(workFlowPanelLayout);
        workFlowPanelLayout.setHorizontalGroup(
            workFlowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workFlowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workFlowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        workFlowPanelLayout.setVerticalGroup(
            workFlowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workFlowPanelLayout.createSequentialGroup()
                .addGroup(workFlowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(workFlowPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workFlowPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("workFlowPanel.TabConstraints.tabTitle"), workFlowPanel); // NOI18N

        jTabbedPane1.setBounds(0, 90, 600, 470);
        jLayeredPane1.add(jTabbedPane1, javax.swing.JLayeredPane.MODAL_LAYER);

        shopInfoHeader.setBackground(resourceMap.getColor("shopInfoHeader.background")); // NOI18N
        shopInfoHeader.setFont(resourceMap.getFont("shopInfoHeader.font")); // NOI18N
        shopInfoHeader.setForeground(resourceMap.getColor("shopInfoHeader.foreground")); // NOI18N
        shopInfoHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopInfoHeader.setText(resourceMap.getString("shopInfoHeader.text")); // NOI18N
        shopInfoHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, resourceMap.getColor("shopInfoHeader.border.highlightOuterColor"), resourceMap.getColor("shopInfoHeader.border.highlightInnerColor"), null, null)); // NOI18N
        shopInfoHeader.setName("shopInfoHeader"); // NOI18N
        shopInfoHeader.setOpaque(true);
        shopInfoHeader.setBounds(250, 34, 310, 50);
        jLayeredPane1.add(shopInfoHeader, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel shopInfoHeader;
    private javax.swing.JPanel workFlowPanel;
    // End of variables declaration//GEN-END:variables

}
