/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AFShopInfo.java
 *
 * Created on Aug 9, 2009, 9:32:15 PM
 */

package com.wms.antifreeze.gui;

import com.wms.antifreeze.AFMgr;
import com.wms.antifreeze.entity.AFShopEntity;
import com.wms.antifreeze.gui.AFViewMgrInterface.AFColor;
import com.wms.util.gui.GUILogInterface;

/**
 *
 * @author Matt
 */
public class AFShopInfo extends javax.swing.JDialog {

    /** Creates new form AFShopInfo */
    AFShopEntity afShopInfo = null;
    AFMgr afMgr = null;
    AFViewMgrInterface afViewMgr = null;
    private boolean appStarted = false;

    public AFShopInfo(GUILogInterface log, java.awt.Frame parent, AFViewMgrInterface afViewMgr, AFMgr afMgr ) {
        super(parent);
        this.afMgr = afMgr;
        this.afViewMgr = afViewMgr;
        
        initComponents();
        appStarted = true;
        afShopInfo = afMgr.getShopInfo();
        displayShopInfo();

    }

    public void updateShopInfo()
    {
        afShopInfo.setAfshopName(afShopNameField.getText(), afMgr != null );
        afShopInfo.setAfshopAddr1(this.afStreetAddr1Field.getText(),afMgr != null );
        afShopInfo.setAfshopAddr2(this.afStreetAddr2Field.getText(), afMgr != null );
        afShopInfo.setAfshopCountryCode(this.afZipField.getText(), afMgr != null );
        afShopInfo.setAfLocale(this.afStateField.getText(), afMgr != null );
        afShopInfo.setAfshopFax(this.afFaxField.getText(), afMgr != null );
        afShopInfo.setAfShopPhone1(this.afPhoneField.getText(), afMgr != null );
        afShopInfo.setAfShopCell(this.afCellField.getText(), afMgr != null );
        afShopInfo.setAfshopCity( this.afCityField.getText(), afMgr != null );


    }

    public void displayShopInfo()
    {
        if( !appStarted )
            return;
        this.afShopNameField.setText( afShopInfo.getAfshopName());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        afShopNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        afCityField = new javax.swing.JTextField();
        afStateField = new javax.swing.JTextField();
        afZipField = new javax.swing.JTextField();
        afStreetAddr1Field = new javax.swing.JTextField();
        afStreetAddr2Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        afPhoneField = new javax.swing.JTextField();
        afCellField = new javax.swing.JTextField();
        afFaxField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        shopInfoHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getResourceMap(AFShopInfo.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setBounds(0, 0, 620, 410);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(resourceMap.getColor("jPanel1.border.highlightColor"), resourceMap.getColor("jPanel1.border.shadowColor"))); // NOI18N
        jPanel1.setForeground(afViewMgr.getColorFromAFColor(AFViewMgrInterface.AFColor.InnerPanel));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel2.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel2.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel2.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setOpaque(true);

        afShopNameField.setText(resourceMap.getString("afShopNameField.text")); // NOI18N
        afShopNameField.setName("afShopNameField"); // NOI18N
        afShopNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afShopNameFieldActionPerformed(evt);
            }
        });

        jLabel3.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel3.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel3.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setOpaque(true);

        jLabel4.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel4.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel4.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setOpaque(true);

        jLabel5.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel5.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel5.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setOpaque(true);

        jLabel6.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel6.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel6.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setOpaque(true);

        jLabel7.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel7.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel7.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setOpaque(true);

        afCityField.setText(resourceMap.getString("afCityField.text")); // NOI18N
        afCityField.setName("afCityField"); // NOI18N

        afStateField.setText(resourceMap.getString("afStateField.text")); // NOI18N
        afStateField.setName("afStateField"); // NOI18N

        afZipField.setText(resourceMap.getString("afZipField.text")); // NOI18N
        afZipField.setName("afZipField"); // NOI18N

        afStreetAddr1Field.setText(resourceMap.getString("afStreetAddr1Field.text")); // NOI18N
        afStreetAddr1Field.setName("afStreetAddr1Field"); // NOI18N

        afStreetAddr2Field.setText(resourceMap.getString("afStreetAddr2Field.text")); // NOI18N
        afStreetAddr2Field.setName("afStreetAddr2Field"); // NOI18N

        jLabel8.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel8.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel8.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setOpaque(true);

        jLabel9.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel9.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel9.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setOpaque(true);

        jLabel10.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelBack));
        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setForeground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.LabelFore));
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setOpaque(true);

        afPhoneField.setText(resourceMap.getString("afPhoneField.text")); // NOI18N
        afPhoneField.setName("afPhoneField"); // NOI18N

        afCellField.setText(resourceMap.getString("afCellField.text")); // NOI18N
        afCellField.setName("afCellField"); // NOI18N

        afFaxField.setText(resourceMap.getString("afFaxField.text")); // NOI18N
        afFaxField.setName("afFaxField"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(afStreetAddr1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(afStreetAddr2Field)
                            .addComponent(afShopNameField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(afStateField)
                                    .addComponent(afCityField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(afZipField)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(afFaxField)
                            .addComponent(afCellField)
                            .addComponent(afPhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(afShopNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(afStreetAddr1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afStreetAddr2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(afCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(afPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(afStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(afCellField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(afZipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(afFaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1.setBounds(30, 90, 530, 260);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        shopInfoHeader.setBackground(resourceMap.getColor("shopInfoHeader.background")); // NOI18N
        shopInfoHeader.setFont(resourceMap.getFont("shopInfoHeader.font")); // NOI18N
        shopInfoHeader.setForeground(resourceMap.getColor("shopInfoHeader.foreground")); // NOI18N
        shopInfoHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopInfoHeader.setText(resourceMap.getString("shopInfoHeader.text")); // NOI18N
        shopInfoHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, resourceMap.getColor("shopInfoHeader.border.highlightOuterColor"), resourceMap.getColor("shopInfoHeader.border.highlightInnerColor"), null, null)); // NOI18N
        shopInfoHeader.setName("shopInfoHeader"); // NOI18N
        shopInfoHeader.setOpaque(true);
        shopInfoHeader.setBounds(250, 34, 310, 50);
        jLayeredPane1.add(shopInfoHeader, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afShopNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afShopNameFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_afShopNameFieldActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        updateShopInfo();
    }//GEN-LAST:event_jButton1MousePressed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afCellField;
    private javax.swing.JTextField afCityField;
    private javax.swing.JTextField afFaxField;
    private javax.swing.JTextField afPhoneField;
    private javax.swing.JTextField afShopNameField;
    private javax.swing.JTextField afStateField;
    private javax.swing.JTextField afStreetAddr1Field;
    private javax.swing.JTextField afStreetAddr2Field;
    private javax.swing.JTextField afZipField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel shopInfoHeader;
    // End of variables declaration//GEN-END:variables

}
