/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AFDetailViewer.java
 *
 * Created on Aug 27, 2009, 11:28:34 AM
 */

package com.wms.antifreeze.view;


import com.wms.antifreeze.AFSearchInterface.AFCustomerSearchField;
import com.wms.antifreeze.entity.ticket.AFTicketInf;
import com.wms.antifreeze.AFMgr;
import com.wms.antifreeze.AFSearchAdaptor;
import com.wms.antifreeze.AFSearchInterface;
import com.wms.antifreeze.gui.AFViewMgrInterface;
import com.wms.antifreeze.gui.AFViewMgrInterface.AFAction;
import com.wms.util.gui.GUILogInterface;
import javax.swing.Icon;
import javax.swing.JDialog;
import org.jdesktop.application.Action;

/**
 *
 * @author Matt
 */
public class AFDetailViewer extends JDialog implements AFSearchAdaptor{

    private AFViewMgrInterface afViewMgr;
    AFCustomerView newCustomerViewForTicket;
    AFSearchInterface afSearchInf;


    private static AFMgr afMgr = null;

    static
    {
        afMgr = AFMgr.callMgr();
    }

    /** Creates new form AFDetailViewer
     * @param afAction
     * @param parent
     * @param modal
     */
    public AFDetailViewer(AFAction afAction, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        afMgr.setTicketSearchField(AFCustomerSearchField.CusLastName);
        initComponents();
    }

    /**
     * 
     * @param afAction
     * @param log
     * @param parent
     * @param afViewMgr
     * @param afMgr
     */
    public AFDetailViewer(AFAction afAction, GUILogInterface log, java.awt.Frame parent, AFViewMgrInterface afViewMgr, AFMgr afMgr)
    {
        super(parent);    
        newCustomerViewForTicket = new AFCustomerView(afAction);
        this.afViewMgr = afViewMgr;
        initComponents();
        AFTicketInf testTicket = afViewMgr.getCurrentTicket();
        if( testTicket != null )
        {
            setMode( testTicket.getAction());
        }
        else
            setMode(afAction);

        newCustomerViewForTicket.setActionButton(afAction);
        AFSkinnableViewPort.add( newCustomerViewForTicket.getPanel());

        
    }

//    public void setAction( AFAction afAction )
//    {
//        this.newCustomerViewForTicket.setActionButton(afAction);
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        BGSkinTag = new javax.swing.JLabel();
        AFHeader = new javax.swing.JLabel();
        AFSkinnableViewPort = new javax.swing.JPanel();
        SearchPanel = new javax.swing.JPanel();
        searchType = new javax.swing.JComboBox();
        SearchWordField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getResourceMap(AFDetailViewer.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setIconImage(null);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLayeredPane1.setBackground(resourceMap.getColor("jLayeredPane1.background")); // NOI18N
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(600, 400));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        BGSkinTag.setIcon(resourceMap.getIcon("BGSkinTag.icon")); // NOI18N
        BGSkinTag.setText(resourceMap.getString("BGSkinTag.text")); // NOI18N
        BGSkinTag.setName("BGSkinTag"); // NOI18N
        BGSkinTag.setBounds(0, 0, 600, 400);
        jLayeredPane1.add(BGSkinTag, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AFHeader.setBackground(resourceMap.getColor("AFHeader.background")); // NOI18N
        AFHeader.setFont(resourceMap.getFont("AFHeader.font")); // NOI18N
        AFHeader.setForeground(resourceMap.getColor("AFHeader.foreground")); // NOI18N
        AFHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AFHeader.setText(resourceMap.getString("AFHeader.text")); // NOI18N
        AFHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, resourceMap.getColor("AFHeader.border.highlightOuterColor"), resourceMap.getColor("AFHeader.border.highlightInnerColor"), null, null)); // NOI18N
        AFHeader.setName("AFHeader"); // NOI18N
        AFHeader.setOpaque(true);
        AFHeader.setBounds(280, 10, 310, 50);
        jLayeredPane1.add(AFHeader, javax.swing.JLayeredPane.MODAL_LAYER);

        AFSkinnableViewPort.setBackground(afViewMgr.getColorFromAFColor( AFViewMgrInterface.AFColor.OutterPanel));
        AFSkinnableViewPort.setName("AFSkinnableViewPort"); // NOI18N
        AFSkinnableViewPort.setOpaque(false);
        AFSkinnableViewPort.setLayout(new java.awt.GridLayout(1, 0));
        AFSkinnableViewPort.setBounds(14, 100, 570, 290);
        jLayeredPane1.add(AFSkinnableViewPort, javax.swing.JLayeredPane.MODAL_LAYER);

        SearchPanel.setBackground(resourceMap.getColor("SearchPanel.background")); // NOI18N
        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("SearchPanel.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, resourceMap.getFont("SearchPanel.border.titleFont"), resourceMap.getColor("SearchPanel.border.titleColor"))); // NOI18N
        SearchPanel.setMinimumSize(new java.awt.Dimension(180, 70));
        SearchPanel.setName("SearchPanel"); // NOI18N
        SearchPanel.setPreferredSize(new java.awt.Dimension(180, 70));

        searchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Last Name", "First Name", "Address", "Home Phone", "Car", "CustomerID" }));
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getActionMap(AFDetailViewer.class, this);
        searchType.setAction(actionMap.get("setSearchType")); // NOI18N
        searchType.setMinimumSize(new java.awt.Dimension(90, 20));
        searchType.setName("searchType"); // NOI18N
        searchType.setPreferredSize(new java.awt.Dimension(90, 22));

        SearchWordField.setText(resourceMap.getString("SearchWordField.text")); // NOI18N
        SearchWordField.setAction(actionMap.get("customerSearch")); // NOI18N
        SearchWordField.setMinimumSize(new java.awt.Dimension(125, 20));
        SearchWordField.setName("SearchWordField"); // NOI18N
        SearchWordField.setPreferredSize(new java.awt.Dimension(125, 20));
        SearchWordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchWordFieldKeyReleased(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                        .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchWordField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        SearchPanel.setBounds(10, 10, 260, 90);
        jLayeredPane1.add(SearchPanel, javax.swing.JLayeredPane.POPUP_LAYER);

        getContentPane().add(jLayeredPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchWordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchWordFieldKeyReleased
        // TODO add your handling code here:
        afMgr.setSearchString(this.SearchWordField.getText());
    }//GEN-LAST:event_SearchWordFieldKeyReleased

    @Action
    public void customerSearch() {
        
        afMgr.setSearchString(this.SearchWordField.getText());
    }

    // GUI manipulation

    public void setMode( AFAction afAction )
    {
        switch( afAction )
        {

        }
    }

    public void setHeader( String newHeader )
    {
        this.AFHeader.setText( newHeader );
    }

    public void setSkin( Icon newSkin)
    {
        this.BGSkinTag.setIconTextGap(0);
        this.BGSkinTag.setIcon(newSkin);
    }

    public void showSearch(boolean flag )
    {
        this.SearchPanel.setVisible(flag);
    }

    public void setSearchPort( AFSearchInterface afSearchInf )
    {
        this.afSearchInf = afSearchInf;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AFHeader;
    private javax.swing.JPanel AFSkinnableViewPort;
    private javax.swing.JLabel BGSkinTag;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JTextField SearchWordField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JComboBox searchType;
    // End of variables declaration//GEN-END:variables

    @Action
    public void invokeSearch() {
        afMgr.setSearchString(this.SearchWordField.getText());
        newCustomerViewForTicket.invokeSearch();

    }

    @Action
    public void setSearchType() {
        AFCustomerSearchField afSearchType;

        //"Last Name", "First Name", "Address", "Home Phone", "Car", "CustomerID"
        String searchFieldTypeStr = (String) this.searchType.getSelectedItem();
        if( searchFieldTypeStr.equals("Last Name"))
            afSearchType = AFCustomerSearchField.CusLastName;
        else if( searchFieldTypeStr.equals("First Name"))
            afSearchType = AFCustomerSearchField.CusFirstName;
        else if( searchFieldTypeStr.equals("Address"))
            afSearchType = AFCustomerSearchField.CusStreet1;
        else if( searchFieldTypeStr.equals("Home Phone"))
            afSearchType = AFCustomerSearchField.CusHome;
        else if( searchFieldTypeStr.equals("Car"))
            afSearchType = AFCustomerSearchField.CusCar;
        else if( searchFieldTypeStr.equals("CustomerID"))
            afSearchType = AFCustomerSearchField.CusID;
        else
            afSearchType = AFCustomerSearchField.Unknown;

        if( afSearchType != AFCustomerSearchField.Unknown)
            afMgr.setCustomerSearchField(afSearchType);
    }

}
