/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AFStarterDialog.java
 *
 * Created on Feb 17, 2010, 11:12:59 AM
 */

package com.wms.antifreeze.view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Matt
 */
public class AFStarterDialog extends javax.swing.JDialog implements Runnable {

    private int jobCheckInterval = 5000;
    private int defHeight = 480;
    private int defWidth = 640;
    private String version = System.getProperty("java.vm.version");
    private String jreName = System.getProperty("java.vm.name");
    private boolean running;

    /** Creates new form AFStarterDialog */
    public AFStarterDialog(java.awt.Frame parent, boolean modal, int min, int max)  {
        super(parent, modal);
        initComponents();
        Dimension defDim = new Dimension(defHeight, defWidth);
//        this.setSize( defDim );
        progressMessage.setText( "Starting to Monitor Start-up" );
        progressNote.setText( "Init Progress System..." );
        jobProgressBar.setMinimum( min );
        jobProgressBar.setMaximum( max );
        progJavaVersion.setText( jreName + " " + version );

        Dimension screenSize = Toolkit.getDefaultToolkit ().getScreenSize ();
        Dimension frameSize = parent.getSize ();

        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;


        setLocation (x - 200, y );
        setVisible(true);

        running = true;
    }

    public void run() {
        while (running)
        {
            try {
                Thread.sleep(this.jobCheckInterval);
                this.repaint();
            } catch (InterruptedException ex) {
//                Logger.getLogger(AFStarterPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public void stop()
    {
        running = false;
    }


    public void setNote( String note )
    {
        progressNote.setText( note );
        System.out.println("AFStarterPanel::setValue - Setting note to: " + note);
    }

    public void setMessage( String message )
    {
        progressMessage.setText( message );
        System.out.println("AFStarterPanel::setValue - Setting message to: " + message);
    }

    public void setMinimum( int min )
    {
        jobProgressBar.setMinimum( min );
    }

    public void setMaximum( int max )
    {
        jobProgressBar.setMaximum( max );
    }

    public void showLogo( boolean flag )
    {
        wmsProductLogo.setVisible( flag );
    }
    public void showVersion( boolean flag )
    {
        progJavaVersion.setVisible( flag );
    }

    public void setValue( int value )
    {
        // if( ParallaxMgr.getMgr() != null )
        //    ParallaxMgr.getMgr().getLog().write( "Setting done value to: " + value );
        System.out.println("AFStarterPanel::setValue - Setting value to: " + value);
        jobProgressBar.setValue( value );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bgSplashPanel = new javax.swing.JPanel();
        afSplashBgImage = new javax.swing.JLabel();
        afSplashInfoPanel = new javax.swing.JPanel();
        wmsProductLogo = new javax.swing.JLabel();
        jobProgressBar = new javax.swing.JProgressBar();
        progressMessage = new javax.swing.JLabel();
        progressNote = new javax.swing.JLabel();
        javaVerLabel = new javax.swing.JLabel();
        progJavaVersion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setUndecorated(true);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.wms.antifreeze.AntiFreezeApp.class).getContext().getResourceMap(AFStarterDialog.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, resourceMap.getColor("jPanel1.border.highlightOuterColor"), resourceMap.getColor("jPanel1.border.highlightInnerColor"), resourceMap.getColor("jPanel1.border.shadowOuterColor"), resourceMap.getColor("jPanel1.border.shadowInnerColor"))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(640, 480));
        jLayeredPane1.setRequestFocusEnabled(false);

        bgSplashPanel.setBackground(resourceMap.getColor("bgSplashPanel.background")); // NOI18N
        bgSplashPanel.setName("bgSplashPanel"); // NOI18N

        afSplashBgImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afSplashBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wms/antifreeze/gui/resources/AFSplash_Shaker_3_1_600_400.png"))); // NOI18N
        afSplashBgImage.setAlignmentY(0.0F);
        afSplashBgImage.setName("afSplashBgImage"); // NOI18N

        afSplashInfoPanel.setBackground(resourceMap.getColor("afSplashInfoPanel.background")); // NOI18N
        afSplashInfoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        afSplashInfoPanel.setMinimumSize(new java.awt.Dimension(550, 225));
        afSplashInfoPanel.setName("afSplashInfoPanel"); // NOI18N
        afSplashInfoPanel.setOpaque(false);

        wmsProductLogo.setForeground(resourceMap.getColor("wmsProductLogo.foreground")); // NOI18N
        wmsProductLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wmsProductLogo.setText("Copyright © 2009 Wintermute Studio - All Rights Reserved."); // NOI18N
        wmsProductLogo.setName("wmsProductLogo"); // NOI18N

        jobProgressBar.setBackground(resourceMap.getColor("jobProgressBar.background")); // NOI18N
        jobProgressBar.setForeground(resourceMap.getColor("jobProgressBar.foreground")); // NOI18N
        jobProgressBar.setName("jobProgressBar"); // NOI18N
        jobProgressBar.setOpaque(false);
        jobProgressBar.setStringPainted(true);

        progressMessage.setBackground(resourceMap.getColor("progressMessage.background")); // NOI18N
        progressMessage.setForeground(resourceMap.getColor("progressMessage.foreground")); // NOI18N
        progressMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressMessage.setText(resourceMap.getString("progressMessage.text")); // NOI18N
        progressMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, resourceMap.getColor("progressMessage.border.highlightOuterColor"), resourceMap.getColor("progressMessage.border.highlightInnerColor"), resourceMap.getColor("progressMessage.border.shadowOuterColor"), resourceMap.getColor("progressMessage.border.shadowInnerColor"))); // NOI18N
        progressMessage.setDoubleBuffered(true);
        progressMessage.setName("progressMessage"); // NOI18N

        progressNote.setBackground(resourceMap.getColor("progressNote.background")); // NOI18N
        progressNote.setForeground(resourceMap.getColor("progressNote.foreground")); // NOI18N
        progressNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressNote.setText(resourceMap.getString("progressNote.text")); // NOI18N
        progressNote.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, resourceMap.getColor("progressNote.border.highlightOuterColor"), resourceMap.getColor("progressNote.border.highlightInnerColor"), resourceMap.getColor("progressNote.border.shadowOuterColor"), resourceMap.getColor("progressNote.border.shadowInnerColor"))); // NOI18N
        progressNote.setName("progressNote"); // NOI18N

        javaVerLabel.setFont(resourceMap.getFont("javaVerLabel.font")); // NOI18N
        javaVerLabel.setForeground(resourceMap.getColor("javaVerLabel.foreground")); // NOI18N
        javaVerLabel.setText(resourceMap.getString("javaVerLabel.text")); // NOI18N
        javaVerLabel.setName("javaVerLabel"); // NOI18N

        progJavaVersion.setFont(resourceMap.getFont("progJavaVersion.font")); // NOI18N
        progJavaVersion.setForeground(resourceMap.getColor("progJavaVersion.foreground")); // NOI18N
        progJavaVersion.setName("progJavaVersion"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setBackground(resourceMap.getColor("jTextPane1.background")); // NOI18N
        jTextPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTextPane1.setEditable(false);
        jTextPane1.setFont(resourceMap.getFont("jTextPane1.font")); // NOI18N
        jTextPane1.setForeground(resourceMap.getColor("jTextPane1.foreground")); // NOI18N
        jTextPane1.setText("The Anti-Frieze suite (SMS) is \"free\" to test and try.\nIf you wish to use it to actually run your shop--Please donate what you think\nAnti - Frieze is worth to you"); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout afSplashInfoPanelLayout = new javax.swing.GroupLayout(afSplashInfoPanel);
        afSplashInfoPanel.setLayout(afSplashInfoPanelLayout);
        afSplashInfoPanelLayout.setHorizontalGroup(
            afSplashInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afSplashInfoPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(progressMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(afSplashInfoPanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(afSplashInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(javaVerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progJavaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afSplashInfoPanelLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(progressNote, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afSplashInfoPanelLayout.createSequentialGroup()
                .addGroup(afSplashInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(afSplashInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wmsProductLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(afSplashInfoPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jobProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
        );
        afSplashInfoPanelLayout.setVerticalGroup(
            afSplashInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afSplashInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jobProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressNote, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(afSplashInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(javaVerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progJavaVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wmsProductLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout bgSplashPanelLayout = new javax.swing.GroupLayout(bgSplashPanel);
        bgSplashPanel.setLayout(bgSplashPanelLayout);
        bgSplashPanelLayout.setHorizontalGroup(
            bgSplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgSplashPanelLayout.createSequentialGroup()
                .addComponent(afSplashInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afSplashBgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgSplashPanelLayout.setVerticalGroup(
            bgSplashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afSplashBgImage, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(afSplashInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bgSplashPanel.setBounds(0, 0, 640, 480);
        jLayeredPane1.add(bgSplashPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AFStarterDialog dialog = new AFStarterDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afSplashBgImage;
    private javax.swing.JPanel afSplashInfoPanel;
    private javax.swing.JPanel bgSplashPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel javaVerLabel;
    private javax.swing.JProgressBar jobProgressBar;
    private javax.swing.JLabel progJavaVersion;
    private javax.swing.JLabel progressMessage;
    private javax.swing.JLabel progressNote;
    private javax.swing.JLabel wmsProductLogo;
    // End of variables declaration//GEN-END:variables

}
