INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '00', 'ADJUSTMENTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '01', 'CAR SYMPTOMS-ENGINE PERFORMANCE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '02', '                          STARTING - LIGHTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '03', '                          NOISES - COMFORTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '04', '                          VIBRATIONS - LEAKS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '05', 'CHECK OUTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '06', 'COMMENTS W/O PRICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '07', 'DIAGNOSTIC CHARGES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '08', 'MILEAGE SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('00', '09', 'ROAD SERVICES & TOWING');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '00', 'AIR CONDITIONING SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '01', 'ALIGNMENT SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '02', 'BATTERY - STARTING & CHARGING');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '03', 'BELTS & HOSES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '04', 'BRAKE SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '06', 'COOLING SYSTEM SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '07', 'IGNITION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '08', 'LIGHTS & SIGNALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '09', 'LUBRICATION & FILTER');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '10', 'MACHINE OPERATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '11', 'MILEAGE SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '12', 'MISCELLANEOUS & ACCESSORIES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '13', 'TIRE & WHEEL SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '14', 'TRANSMISSION SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '15', 'TUNE-UP & MAINTENANCE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '16', 'QUICK JOB COMBINATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '00', 'ANTI LOCK CONTROLS - HYDRAULICS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '01', 'ANTI LOCK - WHEEL UNITS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '03', 'EMERGENCY BRAKE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '05', 'HARDWARE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '06', 'MASTER CYLINDER - HYDRAULICS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '04', 'FRONT BRAKE SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '07', 'REAR BRAKE SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '08', 'TIRE & WHEEL SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '09', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '10', 'QUICK JOB COMBINATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '00', 'AIR CONDITIONING');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '02', 'BELTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '03', 'HOSES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '04', 'ELECTRICAL - FANS - BLOWER MTRS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '05', 'HEATER');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '06', 'RADIATOR - FAN CLUTCH - FAN');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '07', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '08', 'THERMOSTAT - WATER PUMP');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '09', 'QUICK JOB COMBINATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '00', 'AIR SUSPENSION SYSTEM');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '01', 'CONTROL MODULES & COMPUTERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '02', 'FUEL INJECTION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '03', 'IDLE SPEED CONTROLS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '04', 'IGNITION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '05', 'RELAYS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '06', 'RIDE CONTROL & BODY CONTROL MODULE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '07', 'SENSORS & SENDERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '08', 'SOLENOIDS & ACTUATORS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '09', 'SWITCHES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '10', 'VACUUM VALVES & SWITCHES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('04', '11', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '00', 'CLUTCH');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '01', 'DIFFERENTIAL (REAR)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '02', 'DIFFERENTIAL (FRONT) & TRANSAXLE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '03', 'DRIVE SHAFT & U JOINTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '04', 'FRONT AXLES & SHAFTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '05', 'REAR AXLES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '06', 'REAR SUSPENSION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '07', 'TRANSMISSION - TRANSFER CASE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '08', 'TRANSMISSION LINKAGE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('05', '09', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '00', 'BATTERY & STARTING SYSTEM');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '01', 'CHARGING SYSTEM');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '03', 'ELECTRICAL FANS & BLOWER MTRS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '04', 'ELECTRONIC DASH - GAUGES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '05', 'FUSE BOX - FUSES - WIRING');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '06', 'IGNITION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '07', 'LIGHTS & TURN SIGNALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '08', 'RELAYS & SENDERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '02', 'CONTROL SWITCHES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('06', '09', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '00', 'CYLINDER HEAD & VALVE TRAIN');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '01', 'ENGINE - FRONT (TIMING CHAIN,ETC.)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '02', 'ENGINE - LOWER HALF (OIL PAN,ETC.)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '03', 'ENGINE - INTERNAL RELATED REPAIRS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '04', 'ENGINE - OVERHAUL - R & R');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '05', 'ENGINE - REAR (MOUNTS, FILTER, ETC.)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '06', 'FILTERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '07', 'FUEL INJECTION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '08', 'GASKETS & SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '09', 'IGNITION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '10', 'MACHINE OPERATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '11', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '13', 'QUICK JOB COMBINATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '00', 'AIR MGMT SYSTEM - AIR PUMP TYPE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '01', 'COMPUTER CONTROLS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '02', 'EGR SYSTEM');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '03', 'EVAPORATIVE - EMISSIONS - PCV');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '04', 'EXHAUST');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '05', 'FUEL CONTROLLERS - INTAKE MANIFOLD');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '06', 'SENSORS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '07', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('08', '08', 'QUICK JOB COMBINATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '00', 'AIR SUSPENSION,RIDE CONTROL & BCM');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '01', 'ALIGNMENT SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '02', 'BALL JOINTS & STRUTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '04', 'CONTROL ARMS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '05', 'DIFFERENTIAL AND TRANSAXLE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '06', 'FRONT AXLES & SHAFTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '07', 'FRONT SUSPENSION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '08', 'POWER STEERING - PUMP - HOSES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '09', 'REAR AXLES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '10', 'REAR SUSPENSION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '11', 'SPRINGS - SHOCKS - STRUTS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '12', 'STEERING GEAR - RACK & PINION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '13', 'STEERING COLUMN');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '14', 'STEERING LINKAGE - STABILIZERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '15', 'TIRE & WHEEL SERVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '16', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '00', 'CARBURETOR - INTAKE MANIFOLD');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '01', 'CARBURETOR CONTROLS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '02', 'IGNITION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '03', 'ELECTRONIC MODULES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '04', 'FUEL INJECTION');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '05', 'FUEL PUMP - TANK - FILTERS - LINES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '06', 'SENSORS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '07', 'TUNE-UP');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '08', 'TURBO - SUPERCHARGER');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('10', '09', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('11', '00', 'ENGINE      - GASKETS & SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('11', '01', 'FRONT END   - GASKETS & SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('11', '02', 'REAR END    - GASKETS & SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('11', '03', 'TRANS AXLE  - GASKETS & SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('11', '04', 'TRANSMISSION- GASKETS & SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('11', '05', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '00', 'ACCUMULATOR - REC DRIER -  ORIFICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '01', 'BELTS - HOSES - O RING SEALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '03', 'COMPRESSOR & CLUTCH');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '04', 'CONTROLLERS - HEATER CONTROL VALVE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '05', 'EVAPORATOR - CONDENSOR - FAN');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '06', 'HEATER - BLOWER MOTORS - VENT DOORS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '07', 'SWITCHS & RELAYS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '08', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '09', 'QUICK JOB COMBINATIONS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '00', 'ALARMS,BUZZERS & HORN');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '02', 'CABLES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '03', 'CRUISE CONTROL');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '04', 'DASH - CLOCK - RADIO');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '05', 'DOORS - LATCHES & LOCKS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '06', 'ELECTRONIC DASH - GAUGES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '07', 'LIGHTS & SIGNALS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '08', 'SEATS & SAFETY DEVICES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '09', 'SPEEDOMETER & ODOMETER');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '10', 'SUN ROOF & CONVERTIBLE TOP');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '11', 'WINDOWS & MIRRORS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '12', 'WINDSHIELD WIPERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '13', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '00', 'CONTROL SWITCHES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '01', 'DASH REPAIRS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '02', 'ELECTRONIC DASH');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '03', 'GAUGES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '04', 'LIGHT SWITCHES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '05', 'SENDERS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '06', 'SPEEDOMETER & ODOMETER');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '07', 'STEERING COLUMN');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('14', '08', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('15', '00', 'AUTOMATIC & TRANS-AXLES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('15', '01', 'CLUTCH');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('15', '02', 'CONTROLS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('15', '03', 'LINKAGE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('15', '04', 'MANUAL TRANS & TRANS-AXLES');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('15', '05', 'TEST - ADJUST - DIAGNOSE - SERVICE');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('02', '02', 'BRAKE CONTROLS');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('01', '05', 'CAB & SLEEPER SERVICES (HEAVY DUTY)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('03', '01', 'CAB & SLEEPER SERVICES (HEAVY DUTY)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('09', '03', 'CAB & SLEEPER SERVICES (HEAVY DUTY)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('12', '02', 'CAB & SLEEPER SERVICES (HEAVY DUTY)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '01', 'CAB & SLEEPER SERVICES (HEAVY DUTY)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('07', '12', 'TURBO - SUPERCHARGER');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '15', 'WASTE MGMT - AUTO REACH LOADER (McNEILUS)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '16', 'WASTE MGMT - REAR STEER LOADER (PETERSON)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '17', 'WASTE MGMT - REAR SPLIT LOADER (HEIL)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '18', 'WASTE MGMT - REAR SPLIT LOADER (LEACH)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '19', 'WASTE MGMT - REAR SPLIT LOADER (PACK MOR)');
INSERT INTO [JobLvl1] ([Lvl1Code], [Lvl2Code], [JobDesc]) VALUES('13', '14', 'UTILITY - CHERRY PICKER (PRENTICE 120 C-E)');
