INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('1', '0700', 'ACURA');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('2', '0701', 'ALFA ROMEO');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('4', '0702', 'AUDI');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('5', '0800', 'BMW');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('6', '0400', 'BUICK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('7', '0401', 'CADILLAC');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('8', '0402', 'CHEVROLET');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('9', '0007', 'CHEVROLET HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('10', '0200', 'CHRYSLER');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('12', '0201', 'DODGE');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('15', '0300', 'FORD');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('16', '0005', 'FORD HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('18', '0003', 'GMC - LIGHT TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('19', '0007', 'GMC HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('20', '0900', 'HONDA');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('21', '0901', 'HYUNDAI');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('22', '0902', 'INFINITI');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('23', '0009', 'INTERNATIONAL');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('24', '1000', 'ISUZU');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('25', '0010', 'ISUZU HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('26', '1001', 'JAGUAR');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('27', '0102', 'JEEP');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('29', '1002', 'KIA');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('30', '0604', 'LAND ROVER');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('31', '1003', 'LEXUS');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('32', '0301', 'LINCOLN');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('34', '1101', 'MAZDA');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('35', '1102', 'MERCEDES');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('36', '0302', 'MERCURY');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('38', '1200', 'MITSUBISHI');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('39', '0013', 'MITSUBISHI HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('40', '1201', 'NISSAN');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('41', '0014', 'NISSAN HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('42', '0500', 'OLDSMOBILE');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('46', '0202', 'PLYMOUTH');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('47', '0501', 'PONTIAC');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('48', '1301', 'PORSCHE');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('50', '1400', 'SAAB');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('51', '0502', 'SATURN');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('52', '1401', 'STERLING');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('53', '1402', 'SUBARU');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('54', '1500', 'SUZUKI');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('56', '1502', 'TRIUMPH');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('57', '1600', 'VOLKSWAGEN');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('58', '1601', 'VOLVO');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('59', '0017', 'VOLVO HD TRUCK');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('60', '0019', 'WHITE');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('61', '1602', 'YUGO');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('64', '0018', 'WESTERN STAR');
INSERT INTO [Make] ([makeid], [LVL12], [MAKE]) VALUES('65', '1501', 'TOYOTA');
