INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('FREESTYLE', 'FORD', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TACOMA', 'TOYOTA', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1988');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1988');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MUSTANG', 'FORD', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MONTE CARLO FWD', 'CHEVROLET', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('K SERIES 1500-3500 4x4', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('K SERIES 1500-3500 4x4', 'CHEVROLET', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DAKOTA PICK-UP', 'DODGE', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '2007');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' WRANGLER 4x4', 'JEEP', '1989');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ECLIPSE', 'MITSUBISHI', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SRX SUV', 'CADILLAC', '2007');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ALTIMA', 'NISSAN', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SEQUOIA SUV', 'TOYOTA', '2008');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MPV FWD', 'MAZDA', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SAVANA VAN', 'GMC - LIGHT TRUCK', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  FOCUS', 'FORD', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CORVETTE', 'CHEVROLET', '1981');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPEDITION', 'FORD', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('R 1500 PICKUP', 'DODGE', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('FREESTYLE', 'FORD', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('ASCENDER', 'ISUZU', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TAHOE', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  AURORA', 'OLDSMOBILE', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RANGER', 'FORD', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('ASCENDER', 'ISUZU', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  PROTEGE', 'MAZDA', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  RL SERIES AWD', 'ACURA', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('4-RUNNER', 'TOYOTA', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F150 PICK-UP', 'FORD', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPEDITION', 'FORD', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F150 PICK-UP', 'FORD', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAVALIER FWD', 'CHEVROLET', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  LACROSSE', 'BUICK', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  COROLLA FWD', 'TOYOTA', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TOWN & COUNTRY', 'CHRYSLER', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ECLIPSE', 'MITSUBISHI', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' COMANCHE', 'JEEP', '1989');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  FIREBIRD', 'PONTIAC', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RAMCHARGER', 'DODGE', '1989');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  PRELUDE', 'HONDA', '1990');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  TRACER FWD', 'MERCURY', '1993');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('PONTIAC', ' ', '1931');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' GRAND CHEROKEE', 'JEEP', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RANGER', 'FORD', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F150 PICK-UP', 'FORD', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SEPHIA', 'KIA', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SILVERADO PU HYBRID', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('R 1500 PICKUP', 'DODGE', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MUSTANG', 'FORD', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('XTERRA SUV', 'NISSAN', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  IMPALA FWD', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ALTIMA', 'NISSAN', '2007');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' WRANGLER 4x4', 'JEEP', '1989');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TAHOE', 'CHEVROLET', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  BREEZE', 'PLYMOUTH', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  INTRIGUE', 'OLDSMOBILE', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DURANGO', 'DODGE', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CENTURY FWD', 'BUICK', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  PROTEGE', 'MAZDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DAKOTA PICK-UP', 'DODGE', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  S SERIES', 'SATURN', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('VUE', 'SATURN', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  REGENCY 98 FWD', 'OLDSMOBILE', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MUSTANG', 'FORD', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SORENTO', 'KIA', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SILVERADO PU HYBRID', 'CHEVROLET', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ESCORT FWD', 'FORD', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMARO', 'CHEVROLET', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('E250 - E350 VAN', 'FORD', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '1990');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  350Z', 'NISSAN', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  420SEL', 'MERCEDES', '1987');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  OPTIMA', 'KIA', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('K SERIES 1500-3500 4x4', 'CHEVROLET', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RODEO', 'ISUZU', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  PROTEGE', 'MAZDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('AVALANCHE', 'CHEVROLET', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RANGER', 'FORD', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('S-10 PICK-UP', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MALIBU', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  300SD', 'MERCEDES', '1984');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MUSTANG', 'FORD', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MONTERO', 'MITSUBISHI', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('100-150 SERIES PICK-UP', 'DODGE', '1982');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  BEETLE', 'VOLKSWAGEN', '1974');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('PACIFICA', 'CHRYSLER', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SUNFIRE', 'PONTIAC', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DURANGO', 'DODGE', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('PICK UP (HOMBRE)', 'ISUZU', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MONTERO', 'MITSUBISHI', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  DELTA 88 ROYALE', 'OLDSMOBILE', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TOWN & COUNTRY', 'CHRYSLER', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  G20', 'INFINITI', '1993');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' CHEROKEE', 'JEEP', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPLORER', 'FORD', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SEVILLE FWD', 'CADILLAC', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TACOMA', 'TOYOTA', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SORENTO', 'KIA', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '1978');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('CRV', 'HONDA', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  FOCUS', 'FORD', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TROOPER', 'ISUZU', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('G30 RV', ' CHEVROLET', '1990');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMARO', 'CHEVROLET', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RODEO', 'ISUZU', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPLORER', 'FORD', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPRESS 2500-3500 VAN', 'CHEVROLET', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  AVENGER', 'DODGE', '2008');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TAHOE', 'CHEVROLET', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SEDONA VAN', 'KIA', '2007');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('GX470 4x4', 'LEXUS', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  S SERIES', 'SATURN', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SIERRA P-U', 'GMC - LIGHT TRUCK', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  C SERIES P-U C10-C1500', 'GMC - LIGHT TRUCK', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  TAURUS', 'FORD', '1993');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  PROTEGE', 'MAZDA', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  TAURUS', 'FORD', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F150 PICK-UP', 'FORD', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('R 1500 PICKUP', 'DODGE', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  525i', 'BMW', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('S-10 PICK-UP', 'CHEVROLET', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MINI COOPER', 'BMW', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('S-10 PICK-UP', 'CHEVROLET', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMARO', 'CHEVROLET', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MPV FWD', 'MAZDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('CARAVAN -GRAND CARAVAN', 'DODGE', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  LANCER', 'MITSUBISHI', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' GRAND CHEROKEE 4x4', 'JEEP', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DAKOTA PICK-UP', 'DODGE', '1993');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RANGER', 'FORD', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  GRAND AM FWD', 'PONTIAC', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  FOCUS', 'FORD', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  TAURUS', 'FORD', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAVALIER FWD', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAVALIER FWD', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SEBRING', 'CHRYSLER', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('E250 - E350 VAN', 'FORD', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  IMPALA FWD', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('R 1500 PICKUP', 'DODGE', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TACOMA', 'TOYOTA', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('OLDS- SILHOUETTE', 'OLDSMOBILE', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MAXIMA FWD', 'NISSAN', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('UPLANDER VAN', 'CHEVROLET', '2007');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ECLIPSE', 'MITSUBISHI', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  626 FWD', 'MAZDA', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1988');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('NAVIGATOR', 'LINCOLN', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  GRAND PRIX FWD', 'PONTIAC', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('COLORADO P-U', 'CHEVROLET', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPEDITION', 'FORD', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('ASCENDER', 'ISUZU', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('X5 SUV 4x4', 'BMW', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1993');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('ESCAPE SUV', 'FORD', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TRAILBLAZER', 'CHEVROLET', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' CHEROKEE', 'JEEP', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F150 PICK-UP', 'FORD', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ALTIMA', 'NISSAN', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('ASCENDER', 'ISUZU', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  SENTRA', 'NISSAN', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SUBURBAN', 'CHEVROLET', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TRAILER', ' ', '');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  L SERIES', 'SATURN', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RODEO', 'ISUZU', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('VENTURE', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TRAILBLAZER', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CAMRY FWD', 'TOYOTA', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CHEVELLE', 'CHEVROLET', '1972');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  XJ-6', 'JAGUAR', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F250 - F350 PICK UP', 'FORD', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  60 SERIES', 'VOLVO', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DURANGO', 'DODGE', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F150 PICK-UP', 'FORD', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('VOYAGER -GRAND VOYAGER', 'PLYMOUTH', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('CARAVAN -GRAND CARAVAN', 'DODGE', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  XJ-6', 'JAGUAR', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  XJ-6', 'JAGUAR', '1995');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SUBURBAN 4x4', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('DAKOTA PICK-UP', 'DODGE', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('TITAN PICKUP', 'NISSAN', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('XC90', 'VOLVO', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  JETTA FWD', 'VOLKSWAGEN', '1987');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  BEETLE', 'VOLKSWAGEN', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  DeVILLE FWD', 'CADILLAC', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('CARAVAN -GRAND CARAVAN', 'DODGE', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  DTS', 'CADILLAC', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' GRAND CHEROKEE', 'JEEP', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  BONNEVILLE FWD', 'PONTIAC', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPEDITION', 'FORD', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SANDBLASTER', ' ', '');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  PROTEGE', 'MAZDA', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('FRONTIER P-U', 'NISSAN', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  540i', 'BMW', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CONTOUR', 'FORD', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ALTIMA', 'NISSAN', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  BONNEVILLE FWD', 'PONTIAC', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  YUKON 4x4', 'GMC - LIGHT TRUCK', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPLORER', 'FORD', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ALTIMA', 'NISSAN', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('E250 - E350 VAN', 'FORD', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  CIVIC', 'HONDA', '1998');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('EXPLORER', 'FORD', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('RODEO', 'ISUZU', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  626 FWD', 'MAZDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '2003');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  328i', 'BMW', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '1989');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('C SERIES P-U C10-C1500', 'CHEVROLET', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MINI', ' COOPER', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  COUGAR', 'MERCURY', '1994');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  YUKON', 'GMC - LIGHT TRUCK', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACCORD', 'HONDA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ACHIEVA', 'OLDSMOBILE', '1996');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES(' CHEROKEE 4x4', 'JEEP', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('K SERIES 1500-3500 4x4', 'CHEVROLET', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('SIENNA VAN', 'TOYOTA', '2000');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('ODYSSEY', 'HONDA', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('FREESTAR', 'FORD', '2006');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  TAURUS', 'FORD', '1997');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('CRV', 'HONDA', '1999');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MURANO', 'NISSAN', '2004');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  MONTE CARLO RWD', 'CHEVROLET', '1987');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  ES SERIES', 'LEXUS', '2005');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('  INTRIGUE', 'OLDSMOBILE', '2001');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('MONTERO 4x4', 'MITSUBISHI', '2002');
INSERT INTO [Table] ([Model], [Make], [ModYear]) VALUES('F250 - F350 PICK UP', 'FORD', '1996');
