INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('11', '', 'ADVANCED', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('12', '', 'ALLIED SALES', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('13', '', 'AUTOZONE', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('14', '', 'BG', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('15', '', 'LKQ', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('16', '', 'MAIN AUTO', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('17', '', 'MIGHTY', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('18', '', 'MYERS', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('19', '', 'OREILLY', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('20', '', 'PREMIER MAZDA', 'False', 'False', '0', '');
INSERT INTO [Vendor] ([VenID], [ShortDesc], [LongDesc], [AcctsRec], [CurrentList], [Rank], [Group]) VALUES('21', '', 'HEWLETT', 'False', 'False', '0', '');
